name: Simulink CI Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run MATLAB test
        shell: cmd
        run: matlab -batch "run('run_test.m')"

      - name: Export FMU
        shell: cmd
        run: matlab -batch "run('export_fmu.m')"
